GET http://localhost:8080/boolean-model/getResult
Accept: application/json

###
POST http://localhost:8080/saveQuery
Content-Type: application/json

{
  "query": "flu and spanish or ( interior or prevent )"
}

###
GET http://localhost:8080/sequence-search/getResult
Accept: application/json
