GET http://localhost:8080/boolean-model/result
Accept: application/json

###
POST http://localhost:8080/boolean-model/query
Content-Type: application/json

{
  "query": "voter"
}

###
GET https://jsonplaceholder.typicode.com/users
Accept: application/xml
